
--
-- Generated by VASY
--
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY and2 IS
PORT(
  i0	: IN STD_LOGIC;
  i1	: IN STD_LOGIC;
  q	: OUT STD_LOGIC;
  vdd, vss: IN STD_LOGIC
);
END and2;

ARCHITECTURE RTL OF and2 IS
BEGIN
  q <= (i0 AND i1);
END RTL;
