
--
-- Generated by VASY
--
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY or2 IS
PORT(
  i	: IN STD_LOGIC;
  q	: OUT STD_LOGIC;
  vdd, vss: IN STD_LOGIC
);
END or2;

ARCHITECTURE RTL OF or2 IS
BEGIN
  q <= NOT i;
END RTL;
